# Generated by Django 5.2.4 on 2026-02-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_description_category_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, help_text='Internal description for identifying the project in the admin panel.', max_length=200, verbose_name='Admin Description'),
        ),
    ]
