# Generated by Django 6.0.1 on 2026-02-03 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_examples/', verbose_name='Example GIF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category Example',
                'verbose_name_plural': 'Category Examples',
                'ordering': ['created_at'],
            },
        ),
    ]
