# Generated by Django 6.0.1 on 2026-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoryexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_gfx',
            field=models.BooleanField(default=False, help_text='Check this if the category contains static images (no video, no links).', verbose_name='Is GFX Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Project Link'),
        ),
    ]
